config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'targets#index'
  resources :targets, only: %i[index new create show] do
    resources :habits, only: %i[new create show] do
      member do
        put 'update_achieved_status'
        put 'update_active_status'
      end
    end
    resources :small_targets, only: %i[new create show edit update]
  end
  # 再読み込みが発生した際の処理
  get '/users', to: 'users#retake_registration'
  get '/targets/:target_id/habits', to: 'habits#new'
  get '/targets/:target_id/small_targets', to: 'small_targets#new'
end

app/models/target.rb
# 目標に関するデータを管理するためのモデル
class Target < ApplicationRecord
  # アソシエーション
  with_options presence: true do
    validates :name, length: { maximum: 20, allow_blank: true }
    validates :content, length: { maximum: 500, allow_blank: true }
    with_options numericality: { only_integer: true, allow_blank: true } do
      validates :point
      validates :level
      validates :exp
    end
  end

  # バリデーション
  belongs_to :user
  has_many :habits
  has_many :small_targets

  # attr_accessorでインスタンス変数作成すれば、levelとexp要らなかったね

  # レベルと経験値を算出するメソッド
  def self.level_and_exp_calc(point)
    level = point / 10 + 1
    exp = point % 10
    [level, exp]
  end

  # 習慣を達成することで得られるポイントを加算し、レベル・経験値を算出し直すメソッド
  def self.add_point_by_habit_achieve(habit, is_add)
    if is_add
      point = habit.target.point + habit.difficulty_grade + 1
      level, exp = Target.level_and_exp_calc(point)
      habit.target.update(point: point, level: level, exp: exp)
    end
    true
  end

  # 小目標を達成することで得られるポイントを加算し、レベル・経験値を算出し直すメソッド
  def self.add_point_by_small_target_achieve(small_target)
    if small_target.is_achieved
      point = small_target.target.point + small_target.happiness_grade + small_target.hardness_grade
      level, exp = Target.level_and_exp_calc(point)
      small_target.target.update(point: point, level: level, exp: exp)
    end
    true
  end
end

app/controllers/targets_controller.rb
# 目標に関する機能を実装するためのコントローラー
class TargetsController < ApplicationController
  # before_action :current_user, only: [:index, :new]

  def index
    @targets = Target.where(user: current_user).includes(:user)
  end

  def new
    @target = Target.new
  end

  def create
    @target = Target.new(target_params)
    if @target.save
      flash[:success] = '能力値登録完了'
      redirect_to root_path
    else
      flash[:error] = '能力値登録失敗'
      render :new
    end
  end

  def show
    @target = Target.find(params[:id])
    @habits_active = @target.habits.where(is_active: true)
    @habits_not_active = @target.habits.where(is_active: false)
    # 達成状況を配列形式に変換
    @achieved_statuses = []
    @habits_active.each do |habit|
      @achieved_statuses << Habit.translate_achieved_status(habit.achieved_or_not_binary)
    end
  end

  private

  def target_params
    point = params[:target][:point]
    point = 0 if point.nil? # 初期値設定
    level, exp = Target.level_and_exp_calc(point)
    params.require(:target).permit(:name, :content).merge(user: current_user, point: point, level: level, exp: exp)
  end

  # def current_user
  #   @user = User.find(current_user.id)
  # end

  # # 10expでレベルが1上がる設定になっている。(仮設定)
  # def level_and_exp_calc(point)
  #   level = point / 10 + 1
  #   exp = point % 10
  #   [level, exp]
  # end

  # # 二進数データをview表示の形式に置き換える　（HabitsAchievedStatusesControllerにもう一個同じメソッドがあるので統合する必要あり）
  # def set_achieved_status(num_days, achieved_or_not_binary)
  #   status = []
  #   num_days.times do |i|
  #     # 新しい順に判定する
  #     if ((achieved_or_not_binary >> i) & 1) == 1
  #       status.push('〇')    # 新しいデータが先頭になるように格納
  #     else
  #       status.push('×')
  #     end
  #   end
  #   status
  # end
end

app/helpers/targets_helper.rb
module TargetsHelper
end

app/views/targets/index.html.erb
<% breadcrumb :root, current_user %>
<div class="nes-container main">
  <%# 目標の一覧表示 %>
  <div class="nes-container with-title target-lists">
    <h3 class="title"><%= "能力値一覧" %></h3>
    <% @targets.each do |target| %>
    <div class="nes-container with-title target-box">
      <h3 class="title target-name" ><%= link_to target.name, target_path(target) %></h3>
      <div class="target-level" id="target-level"><%= "Lv. " %><%= target.level %></div>
      <div class="target-exp-box">
        <div class="exp-string"><%= "exp:" %></div>
        <progress class="nes-progress is-success exp-bar" value=<%= target.exp %> max="10"></progress>
      </div>
      <%= "設定日：" %><%= l target.created_at %>
    </div>
    <% end %>
  </div>
  <%# /目標の一覧表示 %>

  <%# リンク %>
  <% if flash[:success] != nil %>
  <%= render partial: "shared/ash_talk", locals: {talk_content: flash[:success]} %>
  <% end %>
  <div class="nes-container links">
    <div class="message-list">
      <i class="nes-ash"></i>
      <div class="nes-balloon from-left">
        <%= link_to "ログアウトする？", destroy_user_session_path, method: :delete %>
      </div>
    </div>
    <div class="message-list">
      <i class="nes-ash"></i>
      <div class="nes-balloon from-left">
        <%= link_to "目標を設定する？", new_target_path %>
      </div>
    </div>
  </div>
  <%# /リンク %>
</div>

app/views/targets/new.html.erb
<% breadcrumb :target_new, current_user %>
<div class="nes-container with-title main-form">
  <h2 class="title"><%= "能力値の設定" %></h2>
  <%# 能力値設定の説明 %>
  <div class="instruction">
    <%= render partial: "shared/ash_talk", locals: {talk_content: "達成したい目標、その目標を表す指標となる能力値名をつけよう！"} %>
  </div>
  <%# /能力値設定の説明 %>
  <%# 目標入力フォーム %>
  <%= form_with model: @target, url: targets_path, method: :post, local: true, class: "input-form" do |f| %>
    <% if flash[:error] != nil %>
    <%= render partial: "shared/ash_talk", locals: {talk_content: flash[:error]} %>
    <%= render "shared/error_messages", model: f.object %>
    <% end %>
    <div class="target-content-input-box">
      <%= render partial: "shared/ash_talk", locals: {talk_content: "達成目標を入力しよう！"} %>
      <% f.label :content, "達成目標" %><br />
      <%= f.text_area :content, class: "nes-textarea", placeholder: "3ヶ月で体重を〇〇kgから・・kgに落とす！、YY/MM/DDに受ける予定の〇〇試験に合格する！、など" %>
    </div>
    <div class="target-name-input-box">
      <%= render partial: "shared/ash_talk", locals: {talk_content: "目標に能力値名を名付けよう！" } %>
      <% f.label :name, "能力値名" %><br />
      <%= f.text_field :name, class: "nes-input", placeholder: "美しさ、筋力、英語力、数学力など"%>
    </div>
    <div class="submit-button-box">
      <%= f.submit "登録" %>
    </div>
  <% end %>
  <%# /目標入力フォーム %>
  <div class="message-list">
    <i class="nes-ash"></i>
    <div class="nes-balloon from-left">
      <%= link_to "パラメータ一覧に戻る", root_path %>
    </div>
  </div>
</div>

app/views/targets/show.html.erb
<% breadcrumb :target_show, @target %>
<div class="nes-container with-title main">
  <h2 class="title"><%= "目標詳細表示" %></h2>
  <%# 目標詳細表示の説明 %>
  <div class="instruction">
    <%= render partial: "shared/ash_talk", locals: {talk_content: "ここでは目標に関する詳細を見ることができるよ"} %>
  </div>
  <%# /目標詳細表示の説明 %>
  <%# 目標の詳細表示 %>
  <div class="nes-container with-title target-box">
    <h3 class="title target-name" ><%= @target.name %></h3>
    <div class="target-level" id="target-level">
      <%= "Lv. #{@target.level}" %>
    </div>
    <div class="target-exp-box">
      <div class="exp-string">
        <%= "exp:" %>
      </div>
      <progress class="nes-progress is-success exp-bar" id="exp-bar" value=<%= @target.exp %> max="10"></progress>
    </div>
    <div class="nes-container with-title target-content-box">
      <h3 class="title"><%= '能力値詳細（目標）' %></h3>
      <%= @target.content %>
    </div>
    <%= "設定日：" %><%= l @target.created_at %>
  </div>
  <%# /目標の詳細表示 %>
  <%# リンク %>
  <div class="nes-container links">
    <% if flash[:success] != nil %>
    <%= render partial: "shared/ash_talk", locals: {talk_content: flash[:success]} %>
    <% end %>
    <div class="message-list">
      <i class="nes-ash"></i>
      <div class="nes-balloon from-left">
        <%= link_to "目標の一覧に戻る？", targets_path %>
      </div>
    </div>
  </div>
  <%# /リンク %>
  <%# 習慣一覧 %>
  <div class="nes-container with-title habit-lists">
    <h3 class="title"><%= "鍛錬メニュー（非表示中）" %></h3>
    <div class="active-field hidden">
      <% @habits_active.each_with_index do |habit, i| %>
      <div class="nes-container with-title habit-box-active">
        <h3 class='title'>
          <%= link_to habit.name, target_habit_path(@target, habit), method: :get, id: "habit-show-#{habit.id}" %>
        </h3>
        <div class="inner-content">
          <%= link_to "習慣を中断する", update_active_status_target_habit_path(habit.target, habit, is_active: false), method: :put, class: "nes-btn is-error btn-for-not-active" %>
          <%# 習慣の概要をまとめた部分テンプレート %>
          <%= render partial: "shared/habit_desc", locals: {habit: habit, achieved_status: @achieved_statuses[i]} %>
        </div>
      </div>
      <% end %>
    </div>
    <div class="not-active-field hidden">
      <% @habits_not_active.each_with_index do |habit, i| %>
      <div class="nes-container with-title habit-box-not-active">
        <h3 class='title'><%= habit.name %></h3>
        <%# 習慣の有効化・無効化 %>
        <%= link_to "習慣を再開する", update_active_status_target_habit_path(habit.target, habit, is_active: true), method: :put, class: "nes-btn is-success btn-for-active" %>
      </div>
      <% end %>
    </div>
    <%# 習慣の登録画面へのリンク %>
    <div class="nes-container habit-new-link">
      <i class="nes-ash"></i>
      <div class="nes-balloon from-left">
        <%= link_to "鍛錬メニューを追加する？", new_target_habit_path(@target) %>
      </div>
    </div>
  </div>
  <%# /習慣一覧 %>
  <%# 小目標一覧 %>
  <div class="nes-container with-title small-target-index">
    <h3 class="title"><%= "小目標・達成事項一覧（非表示中）" %></h3>
    <div class="small-target-lists hidden">
      <% @target.small_targets.each_with_index do |small_target, i| %>
      <div class="nes-container with-title small-target-box">
        <h3 class='title'>
          <%= link_to small_target.name, target_small_target_path(@target, small_target), method: :get, id: "small-target-show-#{small_target.id}" %>
        </h3>
        <%= render partial: "shared/small_target_desc", locals: {small_target: small_target} %>
      </div>
      <% end %>
    </div>
    <div class="nes-container small-target-new-link">
      <i class="nes-ash"></i>
      <div class="nes-balloon from-left">
        <%= link_to "小目標・実績を追加する？", new_target_small_target_path(@target) %>
      </div>
    </div>
  </div>
  <%# /小目標一覧 %>
</div>