config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'targets#index'
  resources :targets, only: %i[index new create show] do
    resources :habits, only: %i[new create show] do
      member do
        put 'update_achieved_status'
        put 'update_active_status'
      end
    end
    resources :small_targets, only: %i[new create show edit update]
  end
  # 再読み込みが発生した際の処理
  get '/users', to: 'users#retake_registration'
  get '/targets/:target_id/habits', to: 'habits#new'
  get '/targets/:target_id/small_targets', to: 'small_targets#new'
end

app/models/small_target.rb
class SmallTarget < ApplicationRecord
  # バリデーション
  validates :content, length: { maximum: 500 }
  with_options presence: true do
    validates :name, length: { maximum: 50, allow_blank: true }
    with_options numericality: { only_integer: true, allow_blank: true } do
      with_options if: :is_achieved do
        validates :happiness_grade, numericality: { other_than: 0 }
        validates :hardness_grade, numericality: { other_than: 0 }
      end
      with_options unless: :is_achieved do
        validates :happiness_grade, numericality: { equal_to: 0 }
        validates :hardness_grade, numericality: { equal_to: 0 }
      end
    end
  end
  validates :is_achieved, inclusion: { in: [true, false] }

  def recorded_happiness_and_hardness?
    return false if is_achieved == true && (happiness_grade.zero? || hardness_grade.zero?)

    true
  end

  # アソシエーション
  belongs_to :target

  # # happiness_gradeとhardness_gradeの加工
  # def mod_happiness_and_hardness
  #   return false if is_achieved
  #   happiness_grade = 0
  #   hardness_grade = 0
  #   true
  # end
end

app/controllers/small_targets_controller.rb
class SmallTargetsController < ApplicationController
  before_action :current_target, only: %i[new create show edit update]
  before_action :current_small_target, only: %i[show edit update]

  def new
    @small_target = SmallTarget.new
  end

  def create
    if params[:small_target][:is_achieved] == 'false'
      params[:small_target][:happiness_grade] = 0
      params[:small_target][:hardness_grade] = 0
    end
    # レコード作成
    @small_target = SmallTarget.new(small_target_params)
    # # 目標未達成時のデータ設定
    # @small_target.mod_happiness_and_hardness
    # SmallTarget, TargetモデルへのDB保存とリクエスト
    if create_transaction(@small_target)
      flash[:success] = '登録完了！'
      redirect_to target_path(@target)
    else
      flash[:error] = '登録失敗...'
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    params_tmp = small_target_params
    if params_tmp[:is_achieved].nil?
      params_tmp[:is_achieved] = true
      params_tmp[:happiness_grade] = @small_target.happiness_grade
      params_tmp[:hardness_grade] = @small_target.hardness_grade
    elsif params_tmp[:is_achieved] == 'false'
      params_tmp[:happiness_grade] = 0
      params_tmp[:hardness_grade] = 0
    end
    @small_target_update = SmallTarget.new(params_tmp)
    # SmallTarget, TargetモデルへのDB保存とリクエスト
    if update_transaction(@small_target, @small_target_update)
      flash[:success] = '登録完了！'
      redirect_to target_small_target_path(@target, @small_target), action: :show
    else
      flash[:error] = '登録失敗...'
      current_small_target
      render :edit
    end
  end

  private

  def small_target_params
    params.require(:small_target).permit(:name, :content, :happiness_grade, :hardness_grade, :is_achieved).merge(target: @target)
  end

  def small_target_params_update(small_target)
    { name: small_target.name, content: small_target.content, happiness_grade: small_target.happiness_grade,
      hardness_grade: small_target.hardness_grade, is_achieved: small_target.is_achieved, target: small_target.target }
  end

  def current_target
    @target = Target.find(params[:target_id])
  end

  def current_small_target
    @small_target = SmallTarget.find(params[:id])
  end

  # # happiness_gradeとhardness_gradeの加工
  # def mod_happiness_and_hardness
  #   if @small_target.is_achieved == false
  #     @small_target.happiness_grade = 0
  #     @small_target.hardness_grade = 0
  #   end
  # end

  # # happiness_gradeとhardness_gradeのバリデーション（モデルに移動したほうがいいかな）
  # def recorded_happiness_and_hardness?
  #   return false if @small_target.is_achieved == true && ( @small_target.happiness_grade == 0 || @small_target.hardness_grade == 0 )
  #   return true
  # end

  # 小目標の達成状況と能力値の変動をDBに記録するメソッド
  def create_transaction(small_target)
    ActiveRecord::Base.transaction do
      # 目標達成に対するデータバリデーション
      raise ActiveRecord::Rollback unless small_target.recorded_happiness_and_hardness?
      # 小目標のDB保存
      raise ActiveRecord::Rollback unless small_target.save
      # 目標の経験値・レベルのDB保存
      raise ActiveRecord::Rollback unless Target.add_point_by_small_target_achieve(small_target)

      return true
    end
  end

  # 小目標の達成状況と能力値の変動を更新するメソッド
  def update_transaction(small_target, small_target_update)
    ActiveRecord::Base.transaction do
      prev_achieved = small_target.is_achieved
      next_achieved = small_target_update.is_achieved
      # 未達成への更新は不可
      raise ActiveRecord::Rollback if prev_achieved == true && next_achieved == false
      # 目標達成に対するデータバリデーション
      raise ActiveRecord::Rollback unless small_target_update.recorded_happiness_and_hardness?
      # 小目標のDB保存
      raise ActiveRecord::Rollback unless small_target.update(small_target_params_update(small_target_update))

      # 目標の経験値・レベルのDB保存
      if prev_achieved == false && next_achieved == true
        raise ActiveRecord::Rollback unless Target.add_point_by_small_target_achieve(small_target_update)
      end

      return true
    end
  end
end

app/helpers/small_targets_helper.rb
module SmallTargetsHelper
end

app/views/small_targets/edit.html.erb
<% breadcrumb :small_target_edit, @small_target %>
<div class="nes-container with-title main-form">
  <h2 class="title"><%= "小目標の更新" %></h2>
  <%# 小目標入力フォーム %>
  <%= form_with model: @small_target, url: target_small_target_path(@target, @small_target), method: :put, local: true, class: "input-form" do |f| %>
    <%# エラー表示 %>
    <% if flash[:error] != nil %>
    <%= render partial: "shared/ash_talk", locals: {talk_content: flash[:error]} %>
    <%= render "shared/error_messages", model: f.object %><br />
    <% end %>
    <%# /エラー表示 %>
    <%# 小目標名＆詳細 %>
    <div class="small-target-name-input-box">
      <%= render partial: "shared/ash_talk", locals: {talk_content: "小目標・良くなったことを入力しよう！"} %>
      <% f.label :name, "小目標の内容" %><br />
      <%= f.text_field :name, class: "nes-input", placeholder: "まずは1kg減らすよ!、お出かけをしても体の疲れを感じにくくなった！、など" %>
    </div>
    <div class="small-target-content-input-box">
      <%= render partial: "shared/ash_talk", locals: {talk_content: "詳しく書いてもいいよ！"} %>
      <% f.label :content, "小目標の詳細な内容" %><br />
      <%= f.text_area :content, class: "nes-textarea", placeholder: "記録に残しておくと後で達成した時のことを思い出しやすくなるよ！" %>
    </div>
    <%# /小目標名＆詳細 %>
    <%# 達成状況 %>
    <% if @small_target.is_achieved %>
    <div class="nes-container achieved-result-display">
      <%= render partial: "shared/ash_talk", locals: {talk_content: "この小目標は達成しているよ"} %>
      <%= render partial: "shared/small_target_desc", locals: {small_target: @small_target} %>
    </div>
    <% else %>
    <div class="nes-container achieved-result-input">
      <%= render partial: "shared/ash_talk", locals: {talk_content: "この小目標は達成してる？"} %>
      <%= f.label :is_achieved_true, "達成した" %>
      <%= f.radio_button :is_achieved, true %>
      <%= f.label :is_achieved_false, "まだ達成してない" %>
      <%= f.radio_button :is_achieved, false %>
      <% if f.object.is_achieved == true %>
      <div class="hidden" id="small-target-achieved-pull-down" style='display:block;'>
      <% else %>
      <div class="hidden" id="small-target-achieved-pull-down">
      <% end %>
        <div class='small-target-happiness-input-box'>
          <%= render partial: "shared/ash_talk", locals: {talk_content: "達成した今の気持ちは？(「未達成」以外を選んでね)"} %>
          <% f.label :happiness_grade, "嬉しさ" %><br />
          <div class="nes-select">
            <%= f.collection_select(:happiness_grade, Happiness.all, :id, :name, {}, {}) %>
          </div>
        </div>
        <div class='small-target-hardness-input-box'>
          <%= render partial: "shared/ash_talk", locals: {talk_content: "どれぐらい大変だった？(「未達成」以外を選んでね)"} %>
          <% f.label :hardness_grade, "大変さ" %><br />
          <div class="nes-select">
            <%= f.collection_select(:hardness_grade, Hardness.all, :id, :name, {}, {}) %>
          </div>
        </div>
      </div>
    </div>
    <% end %>
    <%# /達成状況 %>
    <%# フォーム送信 %>
    <div class="submit-button-box">
      <%= f.submit "更新" %>
    </div>
    <%# /フォーム送信 %>
  <% end %>
  <%# /小目標入力フォーム %>
  <div class="message-list">
    <i class="nes-ash"></i>
    <div class="nes-balloon from-left">
      <%= link_to "小目標の表示画面に戻る？", target_path(@target) %>
    </div>
  </div>
</div>

app/views/small_targets/new.html.erb
<% breadcrumb :small_target_new, @target %>
<div class="nes-container with-title main-form">
  <h2 class="title"><%= "小目標の登録" %></h2>
  <%# 本ページの説明 %>
  <div class="instruction">
    <%= render partial: "shared/ash_talk", locals: {talk_content: "ここでは、目標を達成する通過点の目標や、できるようになったことを登録していこう！"} %>
  </div>
  <%# /本ページの説明 %>
  <%# 小目標入力フォーム %>
  <%= form_with model: @small_target, url: target_small_targets_path(@target), method: :post, local: true, class: "input-form" do |f| %>
    <% if flash[:error] != nil %>
    <%= render partial: "shared/ash_talk", locals: {talk_content: flash[:error]} %>
    <%= render "shared/error_messages", model: f.object %><br />
    <% end %>
    <div class="small-target-name-input-box">
      <%= render partial: "shared/ash_talk", locals: {talk_content: "小目標・良くなったことを入力しよう！"} %>
      <% f.label :name, "小目標の内容" %><br />
      <%= f.text_field :name, class: "nes-input", placeholder: "まずは1kg減らすよ!、お出かけをしても体の疲れを感じにくくなった！、など" %>
    </div>
    <div class="small-target-content-input-box">
      <%= render partial: "shared/ash_talk", locals: {talk_content: "詳しく書いてもいいよ！"} %>
      <% f.label :content, "小目標の詳細な内容" %><br />
      <%= f.text_area :content, class: "nes-textarea", placeholder: "記録に残しておくと後で達成した時のことを思い出しやすくなるよ！" %>
    </div>
    <div class="nes-container">
      <%= render partial: "shared/ash_talk", locals: {talk_content: "この目標は達成してる？"} %>
      <%= f.label :is_achieved_true, "達成した" %>
      <%= f.radio_button :is_achieved, true %>
      <%= f.label :is_achieved_false, "まだ達成してない" %>
      <%= f.radio_button :is_achieved, false %>
      <% if f.object.is_achieved == true %>
      <div class="hidden" id="small-target-achieved-pull-down" style='display:block;'>
      <% else %>
      <div class="hidden" id="small-target-achieved-pull-down">
      <% end %>
        <div class='small-target-happiness-input-box'>
          <%= render partial: "shared/ash_talk", locals: {talk_content: "達成した今の気持ちは？(「未達成」以外を選んでね)"} %>
          <% f.label :happiness_grade, "嬉しさ" %><br />
          <div class="nes-select">
            <%= f.collection_select(:happiness_grade, Happiness.all, :id, :name, {}, {}) %>
          </div>
        </div>
        <div class='small-target-hardness-input-box'>
          <%= render partial: "shared/ash_talk", locals: {talk_content: "どれぐらい大変だった？(「未達成」以外を選んでね)"} %>
          <% f.label :hardness_grade, "大変さ" %><br />
          <div class="nes-select">
            <%= f.collection_select(:hardness_grade, Hardness.all, :id, :name, {}, {}) %>
          </div>
        </div>
      </div>
    </div>
    <div class="submit-button-box">
      <%= f.submit "登録" %>
    </div>
  <% end %>
  <%# /小目標入力フォーム %>
  <div class="message-list">
    <i class="nes-ash"></i>
    <div class="nes-balloon from-left">
      <%= link_to "目標の表示画面に戻る？", target_path(@target) %>
    </div>
  </div>
</div>

app/views/small_targets/show.html.erb
<% breadcrumb :small_target_show, @small_target %>
<div class="nes-container with-title main">
  <h2 class="title"><%= "小目標詳細表示" %></h2>
  <%# 小目標詳細表示の説明 %>
  <div class="instruction">
    <%= render partial: "shared/ash_talk", locals: {talk_content: "ここでは小目標の詳細を見ることができるよ！"} %>
  </div>
  <%# /小目標詳細表示の説明 %>
  <%# 小目標詳細 %>
  <div class="nes-container with-title small-target-box">
    <h3 class='title small-target-name'><%= @small_target.name %></h3>
    <%# 嬉しさと大変さ %>
    <%= render partial: "shared/small_target_desc", locals: {small_target: @small_target} %>
    <%# 小目標の内容 %>
    <div class="nes-container with-title small-target-content-box">
      <h3 class='title'><%= "内容" %></h3>
      <%= @small_target.content %>
    </div>
  </div>
  <%# /小目標詳細 %>

  <%# リンク %>
  <div class="nes-container links">
    <div class="message-list">
      <i class="nes-ash"></i>
      <div class="nes-balloon from-left">
        <%= link_to "目標の詳細、小目標一覧を見る？", target_path(@target) %>
      </div>
    </div>
    <div class="message-list">
      <i class="nes-ash"></i>
      <div class="nes-balloon from-left">
        <%= link_to "編集する？", edit_target_small_target_path(@target, @small_target) %>
      </div>
    </div>
  </div>
  <%# /リンク %>
</div>