config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'targets#index'
  resources :targets, only: %i[index new create show] do
    resources :habits, only: %i[new create show] do
      member do
        put 'update_achieved_status'
        put 'update_active_status'
      end
    end
    resources :small_targets, only: %i[new create show edit update]
  end
  # 再読み込みが発生した際の処理
  get '/users', to: 'users#retake_registration'
  get '/targets/:target_id/habits', to: 'habits#new'
  get '/targets/:target_id/small_targets', to: 'small_targets#new'
end

app/views/shared/_ash_talk.html.erb
<div class="message-list">
  <i class="nes-ash"></i>
  <div class="nes-balloon from-left">
    <%= talk_content %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_habit_desc.html.erb
<%# 難易度 %>
<div class="nes-container with-title habit-difficulty">
  <h3 class="title"><%= "難易度" %></h3>
  <div class="difficulty-grade">
    <% (habit.difficulty_grade+1).times do |x| %>
    <i class="nes-icon star"></i>
    <% end %>
  </div>
</div>
<%# 達成状況を表示するテーブル %>
<div class="habit-achieved-status habit-achieved-status-table">
  <h3><%= '達成状況' %></h3>
  <div class="nes-table-responsive">
    <table class="nes-table is-bordered is-centered">
      <tr class="date-row">
        <th><%= l Date.today-6 %></th><th><%= l Date.today-5 %></th><th><%= l Date.today-4 %></th>
        <th><%= l Date.today-3 %></th><th><%= l Date.today-2 %></th><th><%= l Date.today-1 %></th>
        <th><%= l Date.today %>
      </tr>
      <tr class="achieved-status-row">
        <th><%= achieved_status[6] %></th><th><%= achieved_status[5] %></th><th><%= achieved_status[4] %></th>
        <th><%= achieved_status[3] %></th><th><%= achieved_status[2] %></th><th><%= achieved_status[1] %></th>
        <%# 当日のみ達成できたかどうか、のチェック機能をつける %>
        <% if achieved_status[0] == "〇" %>
        <th><%= achieved_status[0] %></th>
        <% else %>
        <th id=<%="achieved-check-cell-#{habit.id}"%> class="tmp1" >
          <%= link_to "達成したらチェック", update_achieved_status_target_habit_path(habit.target, habit), method: :put, id: "habit-achieved-check-#{habit.id}", class: "nes-btn is-success achieve-btn" %>
        </th>
        <% end %>
      </tr>
    </table>
  </div>
</div>

app/views/shared/_small_target_desc.html.erb
<div class="small-target-happiness-hardness">
  <%# 嬉しさ度 %>
  <div class="nes-container with-title small-target-happiness">
    <h3 class="title"><%= "嬉しさ度" %></h3>
    <div class="happiness-grade">
      <% if small_target.happiness_grade == 0 %>
        <% 3.times do |x| %>
        <i class="nes-icon star is-empty"></i>
        <% end %>
      <% else %>
        <% small_target.happiness_grade.times do |x| %>
        <i class="nes-icon star"></i>
        <% end %>
      <% end %>
    </div>
  </div>
  <%# 大変度 %>
  <div class="nes-container with-title small-target-hardness">
    <h3 class="title"><%= '大変だった度' %></h3>
    <div class="hardness-grade">
      <% if small_target.hardness_grade == 0 %>
        <% 3.times do |x| %>
        <i class="nes-icon star is-empty"></i>
        <% end %>
      <% else %>
        <% small_target.hardness_grade.times do |i| %>
        <i class="nes-icon star"></i>
        <% end %>
      <% end %>
    </div>
  </div>
</div>