config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'targets#index'
  resources :targets, only: %i[index new create show] do
    resources :habits, only: %i[new create show] do
      member do
        put 'update_achieved_status'
        put 'update_active_status'
      end
    end
    resources :small_targets, only: %i[new create show edit update]
  end
  # 再読み込みが発生した際の処理
  get '/users', to: 'users#retake_registration'
  get '/targets/:target_id/habits', to: 'habits#new'
  get '/targets/:target_id/small_targets', to: 'small_targets#new'
end

app/models/habit.rb
# 習慣に関するデータを管理するためのモデル
class Habit < ApplicationRecord
  # バリデーション
  validates :content, length: { maximum: 500 }
  with_options presence: true do
    validates :name, length: { maximum: 50, allow_blank: true }
    with_options numericality: { only_integer: true, allow_blank: true } do
      validates :difficulty_grade
      validates :achieved_or_not_binary
      validates :achieved_days, numericality: { less_than: 1_000_000_000, allow_blank: true }
      validates :active_days, numericality: { less_than: 1_000_000_000, allow_blank: true }
    end
  end
  validates :is_active, inclusion: { in: [true, false] }

  # アソシエーション
  belongs_to :target

  # ActiveHashによるアソシエーション
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :difficulty
  belongs_to_active_hash :achieved_status

  # 二進数データをview表示の形式に置き換える
  def self.translate_achieved_status(achieved_or_not_binary)
    display_days = 7
    statuses = []
    display_days.times do |i|
      # 新しい順に判定する
      if ((achieved_or_not_binary >> i) & 1) == 1
        statuses.push('〇') # 新しいデータが先頭になるように格納
      else
        statuses.push('×')
      end
    end
    statuses
  end

  # 日付を跨いだ際にDBの値を変更するメソッド
  def self.update_stat_by_day_progress
    puts " 'Habit.update_stat_by_day_progress' run at #{Time.now} "
    habits = Habit.all
    habits.each do |habit|
      active_days_tmp = if habit.is_active
                          habit.active_days + 1
                        else
                          habit.active_days
                        end
      habit.update(achieved_or_not_binary: habit.achieved_or_not_binary << 1, active_days: active_days_tmp)
    end
  end
end

app/controllers/habits_controller.rb
# 習慣に関する機能を実装するためのコントローラー
class HabitsController < ApplicationController
  before_action :current_target, only: [:new, :create, :show]
  before_action :current_habit, only: [:update_achieved_status, :update_active_status, :show]
  before_action :move_to_target_show, only: :show

  def new
    @habit = Habit.new
  end

  def create
    @habit = Habit.new(habit_params)
    if @habit.save
      flash[:success] = '鍛錬内容の登録完了'
      redirect_to target_path(@habit.target)
    else
      flash[:error] = '鍛錬内容の登録失敗'
      render :new
    end
  end

  # 習慣を今日達成した時にDBの情報を更新し、経験値を獲得する処理を行う
  def update_achieved_status
    if achieved_stat_update_tx(@habit)
      @habit.reload
      flash[:success] = '習慣の達成状況を更新しました'
      # channelを用いて、DBの変更をビューファイルに即時反映
      ActionCable.server.broadcast 'habits_achieved_status_channel', content: @habit
      ActionCable.server.broadcast 'targets_achieved_status_channel', content: @habit.target
    else
      flash[:error] = '習慣の達成状況を更新できませんでした(バグのため、作成者への問い合わせが必要)'
      redirect_to request.referer || root_path
    end
  end

  def show
    # 達成状況を 01 -> ×〇 に変換
    @achieved_status = Habit.translate_achieved_status(@habit.achieved_or_not_binary)
    # 達成率の算出
    @achieved_ratio = calc_achieved_ratio
  end

  # 習慣のアクティブ・非アクティブを変える処理を行う
  def update_active_status
    # 更新の際にactive_daysの日数を変更する(アクティブ状態が変更していて、今日習慣が達成されていない場合)
    active_days_tmp = modify_active_days
    # 更新
    if @habit.update(is_active: params[:is_active], active_days: active_days_tmp)
      flash[:success] = '習慣の状態を更新しました'
      redirect_to request.referer || root_path
    else
      flash[:error] = '習慣の達成状況を更新できませんでした(バグのため、作成者への問い合わせが必要)'
      redirect_to root_path
    end
  end

  private

  def habit_params
    params.require(:habit).permit(:name, :content, :difficulty_grade).merge(target: @target, achieved_or_not_binary: 0, achieved_days: 0, is_active: true)
  end

  # small_targetsコントローラにも同様の記述あり
  def current_target
    @target = Target.find(params[:target_id])
  end

  def current_habit
    @habit = Habit.find(params[:id])
  end

  # 達成状況と能力値の変動をDBに記録するメソッド
  def achieved_stat_update_tx(habit)
    ActiveRecord::Base.transaction do
      is_add = habit.achieved_or_not_binary & 1 # Targetのpointが増えるかどうかを判定
      raise ActiveRecord::Rollback unless habit.update(achieved_or_not_binary: habit.achieved_or_not_binary | 1, achieved_days: habit.achieved_days + 1)
      raise ActiveRecord::Rollback unless Target.add_point_by_habit_achieve(habit, is_add)

      return true
    end
  end

  # アクティブ状態の変更に伴い日数を変更するメソッド
  def modify_active_days
    # アクティブ状態に切り替える かつ 今日、該当習慣を達成していない場合、日数を一日増やす
    if @habit.is_active == false && params[:is_active] == 'true' && (@habit.achieved_or_not_binary & 1).zero?
      @habit.active_days + 1
    # 非アクティブ状態に切り替える かつ 今日、該当習慣を達成していない場合、日数を一日減らす
    elsif @habit.is_active == true && params[:is_active] == 'false' && (@habit.achieved_or_not_binary & 1).zero?
      @habit.active_days - 1
    else
      @habit.active_days
    end
  end

  # アクティブ状態が偽のとき、特定のページを表示させないためのメソッド
  def move_to_target_show
    redirect_to target_path(@target) if @habit.is_active == false
  end

  # 達成率を算出するメソッド
  def calc_achieved_ratio
    achieved_ratio = @habit.achieved_days.to_f / @habit.active_days * 100
    achieved_ratio = 0 if achieved_ratio.nil?
    achieved_ratio.to_i
  end
end

app/helpers/habits_helper.rb
module HabitsHelper
end

app/views/habits/new.html.erb
<% breadcrumb :habit_new, @target %>
<div class="nes-container with-title main-form">
  <h2 class="title"><%= "鍛錬の登録" %></h2>
  <%# 習慣入力フォーム %>
  <%= form_with model: @habit, url: target_habits_path(@target), method: :post, local: true, class: "input-form" do |f| %>
    <% if flash[:error] != nil %>
    <%= render partial: "shared/ash_talk", locals: {talk_content: flash[:error]} %>
    <%= render "shared/error_messages", model: f.object %><br />
    <% end %>
    <div class="habit-name-input-box">
      <%= render partial: "shared/ash_talk", locals: {talk_content: "鍛錬の内容を入力しよう"} %>
      <% f.label :name, "鍛錬の内容" %><br />
      <%= f.text_field :name, class: "nes-input", placeholder: "筋トレを15分やる、参考書の問題を5問解く、など" %>
    </div>
    <div class="habit-content-input-box">
      <%= render partial: "shared/ash_talk", locals: {talk_content: "鍛錬の内容を詳しく入力しよう"} %>
      <% f.label :content, "鍛錬の詳細な内容" %><br />
      <%= f.text_area :content, class: "nes-textarea", placeholder: "腹筋1分、腕立て1分、スクワット1分... 、〇〇のテキストを使用する、など" %>
    </div>
    <div class='habit-difficulty-input-box'>
      <%= render partial: "shared/ash_talk", locals: {talk_content: "鍛錬の難易度を決めよう"} %>
      <% f.label :content, "難易度" %><br />
      <div class="nes-select">
        <%= f.collection_select(:difficulty_grade, Difficulty.all, :id, :name, {}, {}) %>
      </div>
    </div>
    <div class="submit-button-box">
      <%= f.submit "登録" %>
    </div>
  <% end %>
  <%# /習慣入力フォーム %>
  <div class="message-list">
    <i class="nes-ash"></i>
    <div class="nes-balloon from-left">
      <%= link_to "目標の表示画面に戻る？", target_path(@target) %>
    </div>
  </div>
</div>

app/views/habits/show.html.erb
<% breadcrumb :habit_show, @habit %>
<div class="nes-container with-title main">
  <h2 class="title"><%= "鍛錬メニュー詳細表示" %></h2>
  <%# 目標詳細表示の説明 %>
  <div class="instruction">
    <%= render partial: "shared/ash_talk", locals: {talk_content: "ここでは鍛錬の詳細を見ることができるよ！"} %>
  </div>
  <%# /目標詳細表示の説明 %>
  <%# 習慣詳細 %>
  <div class="nes-container with-title habit-box">
    <h3 class='title habit-name'><%= @habit.name %></h3>
    <%# 習慣達成率 %>
    <div class="habit-achieved-ratio-box">
      <div class="achieved-ratio-string">
        <%= "達成率：" %>
      </div>
      <% if @achieved_ratio >= 4.0/7*100 %>
      <progress class="nes-progress is-success achieved-ratio-bar" id="achieved-ratio-bar" value=<%= @achieved_ratio %> max="100"></progress>
      <% elsif @achieved_ratio >= 1.0/7*100 %>
      <progress class="nes-progress is-warning achieved-ratio-bar" id="achieved-ratio-bar" value=<%= @achieved_ratio %> max="100"></progress>
      <% else %>
      <progress class="nes-progress is-error achieved-ratio-bar" id="achieved-ratio-bar" value=<%= @achieved_ratio %> max="100"></progress>
      <% end %>
    </div>
    <%# 難易度、達成状況 %>
    <%= render partial: "shared/habit_desc", locals: {habit: @habit, achieved_status: @achieved_status} %>
    <%# 習慣の内容 %>
    <div class="nes-container with-title habit-content-box">
      <h3 class='title'><%= "鍛錬内容" %></h3>
      <%= @habit.content %>
    </div>
  </div>
  <%# /習慣詳細 %>

  <%# リンク %>
  <div class="nes-container links">
    <div class="message-list">
      <i class="nes-ash"></i>
      <div class="nes-balloon from-left">
        <%= link_to "目標の詳細、鍛錬メニューを見る？", target_path(@target) %>
      </div>
    </div>
  </div>
  <%# /リンク %>
</div>